Made changes to actions
poissonconsulting/universals pull request #6
Opened 2021-11-09 19:53 UTC by MowahidLatif

To maximize the chances of acceptance:

* The title of your PR should briefly describe the change.

* The body of your PR should contain `Fixes #issue-number` (if relevant).

* Commit/merge messages to be included in NEWS.md should begin with `-`.

* Code should follow the tidyverse [style guide](https://style.tidyverse.org).

* Documentation should use roxygen2, with Markdown syntax.

* Contributions should include unit tests (using `testthat`).

For more information see [Contributing](/.github/CONTRIBUTING.md).

2021-11-10 01:16 UTC, aylapear requested changes
The action needs to be re triggered. 

The action has automatically added a new badge but since the names don't match it is adding it a 2nd time. Please replace the R build status badge with the R-CMD-check.

2021-11-12 20:58 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-12 21:10 UTC, MowahidLatif commented
Please merge this branch. Everything is in order.

2021-11-12 22:48 UTC, aylapear approved these changes

2021-11-12 22:49 UTC, aylapear approved these changes

2021-11-12 22:50 UTC, merged